# Generated by Django 3.1.2 on 2020-12-06 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload/')),
            ],
        ),
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.dataset', verbose_name='Dataset')),
                ('results', models.ManyToManyField(blank=True, related_name='results', to='app.File', verbose_name='Résultat')),
                ('targets', models.ManyToManyField(related_name='targets', to='app.File', verbose_name='Cibles')),
            ],
        ),
        migrations.CreateModel(
            name='PdfLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ManyToManyField(related_name='images', to='app.File', verbose_name='Images')),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pdf', to='app.file', verbose_name='PDF')),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='files',
            field=models.ManyToManyField(to='app.File', verbose_name='Fichiers'),
        ),
    ]
