# Generated by Django 3.1.2 on 2020-12-05 15:07

from django.db import migrations
from django.conf import settings

from ..models import Dataset, File

import os


def create_dataset(apps, schema_editor):

    dataset = Dataset.objects.create()
    default_dataset_path = os.path.join(settings.MEDIA_ROOT, "default-dataset")
    files = [f for f in os.listdir(
        default_dataset_path) if os.path.isfile(os.path.join(default_dataset_path, f))]

    for f in files:
        file_db = File.objects.create()
        file_db.file = os.path.join("default-dataset", f)
        file_db.save()
        dataset.files.add(file_db)
        dataset.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_dataset)
    ]
