# Generated by Django 3.1.2 on 2020-12-05 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201205_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.dataset', verbose_name='Dataset')),
                ('results', models.ManyToManyField(related_name='results', to='app.File', verbose_name='Résultat')),
                ('targets', models.ManyToManyField(related_name='targets', to='app.File', verbose_name='Cibles')),
            ],
        ),
    ]
